const homeSection2Transl = () => {
  const bullet1 = {
    // en: "",
    // it: "",
    // tr: "",
    // ro: "",
    // hu: "",
    // ar: "",
    // de: "",
    // es: "",
    // sv: "",
    // pt: "",
    // fi: "",
    // pl: "",
    // th: "",
    // ms: ""

    en: "Access to over 900 assets",
    it: "",
    tr: "",
    ro: "",
    hu: "",
    ar: "الوصول إلى أكثر من 900 أصل",
    de: "",
    es: "",
    sv: "",
    pt: "",
    fi: "",
    pl: "",
    th: "",
    ms: "",
  };
  const bullet2 = {
    en: "Competitive spreads",
    it: "",
    tr: "",
    ro: "",
    hu: "",
    ar: "هوامش بلا منافس",
    de: "",
    es: "",
    sv: "",
    pt: "",
    fi: "",
    pl: "",
    th: "",
    ms: "",
  };
  const bullet3 = {
    en: "Easy to use trading experience",
    it: "",
    tr: "",
    ro: "",
    hu: "",
    ar: "تجربة تداول سهلة ومريحه",
    de: "",
    es: "",
    sv: "",
    pt: "",
    fi: "",
    pl: "",
    th: "",
    ms: "",
  };
  const bullet4 = {
    en: "Fast withdrawals",
    it: "",
    tr: "",
    ro: "",
    hu: "",
    ar: "سحوبات سريعة",
    de: "",
    es: "",
    sv: "",
    pt: "",
    fi: "",
    pl: "",
    th: "",
    ms: "",
  };
  const bullet5 = {
    en: "Beginner/experienced investors",
    it: "",
    tr: "",
    ro: "",
    hu: "",
    ar: "المبتدئين / المستثمرين ذوي الخبرة",
    de: "",
    es: "",
    sv: "",
    pt: "",
    fi: "",
    pl: "",
    th: "",
    ms: "",
  };

  return { bullet1, bullet2, bullet3, bullet4, bullet5 };
};

export default homeSection2Transl;
